# Generated by Django 3.2.4 on 2021-06-16 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='numbers',
            field=models.IntegerField(default=3),
        ),
    ]
