# Generated by Django 3.2.4 on 2021-06-20 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_product_numbers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='numbers',
            field=models.PositiveIntegerField(default=3),
        ),
    ]
